---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

## polmineR and gensim

I used [this](https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/) website as an introduction to gensim and to understand the data structure.

```{r load_packages}
library(reticulate)
library(polmineR)
library(pbapply)
```

```{r import_gensim}
gensim <- import("gensim")
```


```{r data}
use("GermaParl")
```


## The polmineR part

```{r create_matrix}
tdm <- corpus("GERMAPARL") %>%
  as.speeches(s_attribute_name = "speaker") %>%
  as.TermDocumentMatrix(p_attribute = "word")
```


## Preparing the corpus object

We need a list of list with tuples inside ... 

```{r prepare_corpus}
tdm$i <- tdm$i - 1L
py$i <- r_to_py(unname(split(x = tdm$i, f = tdm$j)), convert = TRUE)
py$v <- r_to_py(unname(split(x = tdm$v, f = tdm$j)), convert = TRUE)
py_run_string("corpus = [zip(i[x],v[x]) for x in range(len(i))]")
``` 


## Preparing the dictionary

```{r prepare_dictionary}
Encoding(tdm$dimnames$Terms) <- "UTF-8"
py$terms <- tdm$dimnames$Terms
py_run_string("token2id = dict(zip(terms, range(len(terms))))")
py$dictionary <- gensim$corpora$dictionary$Dictionary()
py_run_string("dictionary.__dict__['token2id'] = token2id")
```

And now we can run the gensim topicmodelling engine.

```{r lda_single_threaded}
started <- Sys.time()
lda_model <- gensim$models$ldamodel$LdaModel(corpus = py$corpus,
                                            id2word = py$dictionary,
                                            num_topics = 25L, 
                                            random_state = 100L,
                                            update_every = 1L,
                                            chunksize = 100L,
                                            passes = 10L,
                                            alpha = "auto",
                                            per_word_topics = TRUE)

finished <- Sys.time()
print(finished - started)
lda_model$print_topics()
```


```{r lda_multi_threaded, eval = FALSE}
lda_model <- gensim$models$ldamulticore$LdaMulticore(corpus = corpus,
                                            id2word = dict,
                                            num_topics = 20L, 
                                            random_state = 100L,
                                            update_every = 1L,
                                            chunksize = 100L,
                                            passes = 10L,
                                            alpha = "auto",
                                            per_word_topics = TRUE,
                                            workers = 5
                                            )

```
